# database: local-postgreSQL
#database:
#  engine: 'django.db.backends.postgresql'
#  name: 'toryn_canteen'
#  host: 'localhost'
#  port: '5432'
#  user: 'toryn'
#  password: '214934'

# database: server-mysql
database:
  engine: 'django.db.backends.mysql'
  name: 'h_db21375077'
  host: '120.46.3.97'
  port: '3306'
  user: 'u21375077'
  password: 'Aa686659'


# aliyun oss
oss:
    oss_access_key_id: "LTAI5tLxeRicGKSwqEFKeS9C"
    oss_access_key_secret: "K2K35vniXgO2e9uqKm3pgZ5HJfM4tc"
    oss_end_point: "oss-cn-beijing.aliyuncs.com"
    oss_bucket_name: "buaaxiaolanshu"
    oss_bucket_alc_type: "public-read"
    oss_prefix_url: "https://"

# secret
django_secret_key: 'django-insecure-3an!c-fug2jf5vi%4(jt$bux$-%sq1d+=sfgjsmryee2sy@76)'

# AI
ai_api_key: ""