# Generated by Django 4.2.3 on 2024-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cafeteria',
            index=models.Index(fields=['id'], name='cafeteria_c_id_d2ff12_idx'),
        ),
        migrations.AddIndex(
            model_name='cafeteria',
            index=models.Index(fields=['name'], name='cafeteria_c_name_d38731_idx'),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['id'], name='cafeteria_c_id_4c41e5_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['id'], name='cafeteria_d_id_126801_idx'),
        ),
    ]
