# Generated by Django 4.2.3 on 2025-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_cafeteria_cafeteria_c_id_d2ff12_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cafeteria',
            name='cafeteria_c_id_d2ff12_idx',
        ),
        migrations.RemoveIndex(
            model_name='cafeteria',
            name='cafeteria_c_name_d38731_idx',
        ),
        migrations.RemoveIndex(
            model_name='counter',
            name='cafeteria_c_id_4c41e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dish',
            name='cafeteria_d_id_126801_idx',
        ),
    ]
