# Generated by Django 4.2.3 on 2024-12-11 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384, verbose_name='文本向量'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='post_post_id_ad6c36_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['dish'], name='post_post_dish_id_c35278_idx'),
        ),
    ]
