# Generated by Django 4.2.3 on 2025-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_vector_post_post_post_id_ad6c36_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_id_ad6c36_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_dish_id_c35278_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vector',
        ),
    ]
