# Generated by Django 4.2.3 on 2025-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_email_7bbb4c_idx_user_user_id_f1790c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_7bbb4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_id_f1790c_idx',
        ),
    ]
